[mypy]
plugins = mypy_django_plugin.main
disallow_any_generics = false
allow_redefinition = true

[mypy.plugins.django-stubs]
django_settings_module = helpdesk.settings

[mypy-helpdesk.settings]
disable_error_code = var-annotated

[mypy-*.migrations.*]
ignore_errors = True
