apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Имя контейнера prometheus в docker-compose
    isDefault: true
    editable: false
