# Generated by Django 5.2 on 2025-05-31 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="status",
            field=models.CharField(
                choices=[
                    ("OP", "Open"),
                    ("IP", "In Progress"),
                    ("RS", "Resolved"),
                    ("WR", "WR"),
                ],
                default="OP",
                max_length=2,
            ),
        ),
    ]
