# Generated by Django 5.2 on 2026-05-08

from django.db import migrations, models
import django.db.models.deletion


def backfill_ticket_priority(apps, schema_editor):
    Ticket = apps.get_model("core", "Ticket")
    for t in Ticket.objects.select_related("category__default_priority").all().iterator():
        if t.priority_id is None and getattr(t.category, "default_priority_id", None):
            t.priority_id = t.category.default_priority_id
            t.save(update_fields=["priority"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.priority",
                verbose_name="Приоритет",
            ),
        ),
        migrations.RunPython(backfill_ticket_priority, migrations.RunPython.noop),
    ]

