# Generated by Django 5.2 on 2025-06-08 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_membership"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="membership",
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
            },
        ),
        migrations.AlterModelTable(
            name="membership",
            table="Membership",
        ),
    ]
