# Generated by Django 5.2 on 2025-06-16 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_membership_options_alter_membership_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="active_tickets_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="membership",
            name="last_ticket_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="resolved_tickets_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="membership",
            name="shift_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="shift_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.organization",
            ),
        ),
    ]
