# Generated by Django 5.2 on 2025-06-20 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_membership_options_alter_membership_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="membership",
            name="unique_active_admin_per_organization",
        ),
        migrations.AlterUniqueTogether(
            name="membership",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="user",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="core.organization",
            ),
        ),
    ]
