# Generated by Django 5.2.13 on 2026-05-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_kb_fulltext_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="resolved_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Фактическое время решения"
            ),
        ),
    ]
