# Generated by Django 5.2 on 2025-06-18 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_user_last_organization_leave_application"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
            },
        ),
        migrations.AlterModelTable(
            name="application",
            table="Application",
        ),
    ]
