# Generated by Django 5.2 on 2025-06-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_application_options_alter_application_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="resolution_approved",
            field=models.BooleanField(
                default=False, verbose_name="Resolution approved by requestor"
            ),
        ),
    ]
